from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome(executable_path="C:\\Users\\ASUS-PC\\PycharmProjects\\selenium-nazia\\drivers\\chromedriver.exe")
driver.maximize_window()
driver.get("http://127.0.0.1:8000/accounts/login/")
print(driver.current_url)
driver.find_element_by_id('id_username').send_keys("naziatabassum")
print("find username field\n")
driver.find_element_by_id('id_password').send_keys("nazianazia")
print("find password field\n")
time.sleep(2)
driver.find_element_by_id('login_id').click()
print("find username field\n")
driver.find_element_by_name('Insert').click()
time.sleep(4)
driver.find_element_by_name('InsertHouse').click()
time.sleep(4)
driver.find_element_by_name('InsertAddress').click()
time.sleep(4)
driver.find_element_by_name('city').send_keys('Dhaka')
driver.find_element_by_name('house_no').send_keys('20')
driver.find_element_by_name('road_no').send_keys('6')
driver.find_element_by_name('area').send_keys('Mohammadpur')
driver.find_element_by_id('a_id').click()
address=driver.find_element_by_name('address')
time.sleep(2)
driver.close()

print("succesful")